apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  replicas: {{ .Values.users.replicaCount }}
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: gateway
        image: "{{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag }}"
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c"]
        args:
          - "uvicorn main:app --host 0.0.0.0 --port 8000"
        ports:
          - containerPort: {{ .Values.gateway.containerPort }}
        envFrom:
          - configMapRef:
              name: gateway-env