apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
spec:
  replicas: {{ .Values.orders.replicaCount }}
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: "{{ .Values.orders.image.repository }}:{{ .Values.orders.image.tag }}"
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c"]
        args:
        - "uvicorn main:app --host 0.0.0.0 --port 8000 --loop asyncio"
        ports:
          - containerPort: {{ .Values.orders.containerPort }}
        envFrom:
          - configMapRef:
              name: orders-env