apiVersion: v1
kind: Service
metadata:
  name: orders
spec:
  selector:
    app: orders
  ports:
    - name: http
      port: 8000
      targetPort: {{ .Values.orders.containerPort }}
  type: ClusterIP