global:
  environment: dev
  host: api.dev.local

ingress:
  enabled: true
  className: nginx
  path: /

secrets:
  jwtSecretKey: dev-super-secret

gateway:
  replicaCount: 1
  containerPort: 8000
  image:
    repository: roxanaiuliamiu/k-api-gateway
    tag: latest

users:
  replicaCount: 1
  containerPort: 8000
  image:
    repository: roxanaiuliamiu/k-users
    tag: latest

orders:
  replicaCount: 1
  containerPort: 8000
  image:
    repository: roxanaiuliamiu/k-orders
    tag: latest